### ISSUE TITLE
Radio/Players do not resume when loading world

### ISSUE THREAD

**Issue by NicholasFeldman** [Stumblinbear/BetterRecords#11]
When the game is quit with a radio playing, it will error and will require the player to remove and replace the tuning crystal.

From [/u/CountPixel](https://www.reddit.com/user/CountPixel)

**Comment by AngrySoundTech** [comment]
This requires a bit more logic to be re-written. I've stopped the error from showing when you quit the game, but the record is still required to be re-inserted when the world loads. Putting this off until after stuff like shuffling is fixed, because the way music is played might change

**Comment by NicholasFeldman** [comment]
Transferred issue to new repository
