### ISSUE TITLE
Unable to etch blank record, "No record to etch"

### ISSUE THREAD

**Issue by Hellsinger222** [Stumblinbear/BetterRecords#16]
This mod is really nice but I cant etch a record! Every time I try to, it says "No record to etch" I have a blank record in and I know I put the right link in right!

**Comment by Hellsinger222** [comment]
Mc version: 1.9.4 .
Mod version: 1.4.1 .
Forge version: I had it on (1976) but I switched to the latest(2051) to see if that was the problem.
Steps to reproduce: none really unless this mod has any mod incompatibility's?

**Comment by AngrySoundTech** [comment]
I'm unable to reproduce this bug.

It might be an issue with the mp3 you are trying to use. Let me know if the following mp3 works for you:

https://ia802508.us.archive.org/5/items/testmp3testfile/mpthreetest.mp3

**Comment by Hellsinger222** [comment]
omg I guess i am not doing the mp3 right! because that link just worked!

**Comment by AngrySoundTech** [comment]
How are you doing the mp3 then? Let's see the link you're trying to use.

**Comment by Hellsinger222** [comment]
https://www.dropbox.com/s/81cu8b3d7e0iak3/AC-DC%20-%20Hells%20Bells.mp3?dl=0

**Comment by Hellsinger222** [comment]
https://www.dropbox.com/home?preview=AC-DC+-+Hells+Bells.mp3#
sorry this one!

**Comment by Hellsinger222** [comment]
nvm i got it working!

**Comment by steedo100** [comment]
Hi. I have run into this very problem. Your test link worked but Hellslinger's file links didn't. I am using minecraft 1.7.10 with the latest forge available to it. I have tried uploading to dropbox with ogg and mp3 files. with links 
https://www.dropbox.com/s/vyni6pcjner2e11/Token%20-%20Doozy%20(Official%20Music%20Video).ogg?dl=0 (Before the download page on dropbox)
And
https://www.dropbox.com/s/vyni6pcjner2e11/Token%20-%20Doozy%20(Official%20Music%20Video).ogg?dl=0# (For the actual download link off dropbox) 

And the same for mp3 files. 
https://www.dropbox.com/s/cl2ztiynxoseajh/Token%20-%20Doozy%20(Official%20Music%20Video).mp3?dl=0# (Direct from dropbox)

https://www.dropbox.com/s/cl2ztiynxoseajh/Token%20-%20Doozy%20%28Official%20Music%20Video%29.mp3?dl=0 (Share link)

**Comment by NicholasFeldman** [comment]
The link you're trying to use isn't a direct link to an mp3 file.

In order to use a file from dropbox, you must link directly to the file as such:
https://www.dl.dropboxusercontent.com/s/cl2ztiynxoseajh/Token%20-%20Doozy%20(Official%20Music%20Video).mp3?dl=0#
When viewed in your browser, a link to an mp3 file should look like the following:

![Example of proper mp3](https://puu.sh/xtNIJ/283eabafe5.png)

**Comment by steedo100** [comment]
Thats brilliant stuff ive got it working! I love the mod its one of the best. Thanks for the quick reply i appreciate it.



Sent from my Samsung Galaxy smartphone.

-------- Original message --------
