### ISSUE TITLE
Crash when destroying record player playing record in creative on server

### ISSUE THREAD

**Issue by InuYasha86000** [Stumblinbear/BetterRecords#17]
I got a crash just now while playing on my modpack which has betterrecords, I was on my server with a friend of mine playing a record I had etched and the lid on the record player was stuck down so I could not remove the record. we were both in creative mode so I decided to destroy the record player, when I destroyed it, my screen froze and then my minecraft crashed, only my minecraft crashed as my friend was still on the server and the server did not crash either.
here is the crash report: http://pastebin.com/mHBXUttt

**Comment by AngrySoundTech** [comment]
This bug has already been fixed in b887de1.

Be advised that 1.7.10 is no longer being supported, as most mods are making the push to update to 1.10
