### ISSUE TITLE
Client crash when chunk in server unloads that contains record player 1.7.10

### ISSUE THREAD

**Issue by InuYasha86000** [Stumblinbear/BetterRecords#18]
Myself and someone else have discovered a bug where if you leave a playing record player and the chunk it's in unloads it will crash the client side, the server remains up though:
http://pastebin.com/SsfvTXkk
and Yes this is in 1.7.10, yes I know 1.7.10 is no longer supported but this is a game breaking bug and someone else had this happen as well as they left a message in the comments on the curse page.

**Comment by AngrySoundTech** [comment]
This bug was already fixed in commit b887de1.

I understand that this is a game breaking bug, but 1.7.10 is still no longer being supported, as most mods are already updated to 1.10. At this point, it wouldn't be worth the effort to maintain two branches of the project.
