### ISSUE TITLE
Incompatibility with lastest Forge

### ISSUE THREAD

**Issue by MastaC729** [Stumblinbear/BetterRecords#20]
Forge version: 2221
BetterRecords version: latest 1.10.2 commit

Issue: Server crashes with the following stacktraces: http://pastebin.com/k9b4CyPf

Steps to reproduce: Run BetterRecords with FoamFix installed as well

I understand that this conflict is due to FoamFix, but I am just wondering if you would be interested in resolving this crash? Not sure what optimizations FoamFix is making to IItemColor, but overall the anarchy version has been found to drastically decrease RAM usage on our modpack. Let me know if you need any additional information.

EDIT: Issue seems to be related to the version of Forge, not sure why.

**Comment by AngrySoundTech** [comment]
Does this only occur with the Anarchy version of FoamFix? At a quick glance it doesn't seem like FoamFix is making any changes to IItemColor. Either way, if this occurs because of FoamFix, it would need to be fixed on their side, although I don't know how they support things like this.

Tagging @asiekierka just in case this is actually an issue on their end.

**Comment by asiekierka** [comment]
Please update FoamFix to 0.5.4 (not 0.5.4-beta2).

**Comment by MastaC729** [comment]
I can confirm that this still happens on the 0.6.0-beta3 Anarchy version of Foamfix. My apologies for not mentioning that I'm using the Anarchy version, as I know it is much more invasive.

**Comment by asiekierka** [comment]
If this particular issue happens with *Lawful*, it's probably not related to FoamFix at all and merely a coincidence.

Could you send me the stacktrace from Lawful?

**Comment by MastaC729** [comment]
http://pastebin.com/d7HT8j30

It hadn't occurred to me that FoamFix might not be the culprit, considering the crash report I was getting. So then I tested it without any mods, and lo and behold it was crashing with no other mods installed.

**Comment by AngrySoundTech** [comment]
What is the exact forge version you are trying it on then? Also, When you say "latest 1.10.2 commit" do you mean 2a55ca or 01e04e8?

Also, thank you @asiekierka for your help, and sorry for the bother.

**Comment by MastaC729** [comment]
I am using the latest 1.10.2 Forge, version 2234, and when I say latest 1.10.2 commit I mean a58796e.

**Comment by AngrySoundTech** [comment]
I just updated everything and we're now building against forge 2234, Try it as of 2b7cab1 and let me know how it works out.

Previously, we were still building against an older version of forge, which had a number of api changes.

**Comment by MastaC729** [comment]
Nope, that didn't fix the issue. From what I can see in the crash log it seems to be related to this line: 

`Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.color.IItemColor`

Now I haven't read your source code too intensively yet, but wouldn't it make sense that the server is crashing because it's trying to access this client-only class?

**Comment by AngrySoundTech** [comment]
The runtime error has been resolved, but has spawned issue #21. This separate will be tracked there, and will be fixed during the code refactor I am working on.

Thank you for your report and your suggestion, they both helped quickly resolve the problem.

**Comment by MastaC729** [comment]
Awesome, thanks for the quick turnaround. Finally I can play my favorite meme-related music on our server again. ;)
