### ISSUE TITLE
Game volume setting affects music radius rather than volume

### ISSUE THREAD

**Issue by Azulaloi** [Stumblinbear/BetterRecords#28]
This is more prominent the lower the volume settings. Standing next to a speaker while lowering the volume does not lower the music volume, but the volume dropoff becomes extremely pronounced. 

For example, a small speaker with a Master Volume at 3% is fully audible and much louder than the game while standing on it, but becomes completely inaudible after 4 blocks.

**Comment by NicholasFeldman** [comment]
Transferred issue to new repository
