### ISSUE TITLE
Wire lenght

### ISSUE THREAD

**Issue by marekvac** [Stumblinbear/BetterRecords#33]
Hi I have this mod on 1.7.10. I have a big theatre and i want a sound hear everywhere. But wire lenght is only 6 blocks. I need at least 30 blocks min. Exist a some fix for this?
Sorry for my English im Czech.

**Comment by NicholasFeldman** [comment]
1.7.10 is no longer being updated or maintained, as I work on new features for the 1.10.2 release.

In 1.7.10, speakers increase the radius of the music from the player. This is being considered for change in a future update.
