### ISSUE TITLE
Mekanism incompatibility ?

### ISSUE THREAD

**Issue by Ouack23** [Stumblinbear/BetterRecords#35]
Hi, I'm having this error when launching minecraft 1.10.2 with BetterRecords-1.10.2-1.5.0-beta.3.jar

[https://pastebin.com/tWa111gT](https://pastebin.com/tWa111gT)

Whitout Better Records, the game works fine.
Java 1.8.151 x64 / Windows 10 64 bits / modlist in pastebin

Hope this helps,
Ouack23

**Comment by NicholasFeldman** [comment]
Duplicate of #34, track this there.

**Comment by NicholasFeldman** [comment]
The fix has been released, and is awaiting CurseForge's approval:
 https://minecraft.curseforge.com/projects/better-records/files/2499608
