### ISSUE TITLE
Shift clicking blank record or crystal into etcher / tuner crashes game

### ISSUE THREAD

**Issue by NicholasFeldman** [Stumblinbear/BetterRecords#39]
[crash-2017-12-18_17.08.04-client.txt](https://github.com/Stumblinbear/BetterRecords/files/1569611/crash-2017-12-18_17.08.04-client.txt)
[crash-2017-12-18_17.09.22-client.txt](https://github.com/Stumblinbear/BetterRecords/files/1569612/crash-2017-12-18_17.09.22-client.txt)

**Comment by nnystyxx** [comment]
I also get this crash when I so much as hover over the record in my inventory

**Comment by NicholasFeldman** [comment]
@nnystyxx
The same crash? That shouldn't be possible.

There's no way something like hovering over it and crashing would have slipped through testing. Please open a separate issue and provide your crash log.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Stumblinbear/BetterRecords/issues/43

**Comment by NicholasFeldman** [comment]
Totally didn't accidentally commit this to master.
