### ISSUE TITLE
Different records keep playing the same song

### ISSUE THREAD

**Issue by Acdrybones** [Stumblinbear/BetterRecords#4]
Not sure if this has been looked into or not, but diffrent records I etch keep playing the 1st song I etched. For some reason, not everyone is having this problem, but me and my friend are. Thanks!

**Comment by AngrySoundTech** [comment]
I need a bit more information. Could you please provide the following:

* Minecraft Version
* Mod Version
* Forge Version
* Steps to reproduce

**Comment by Acdrybones** [comment]
I'm using 1.7.10, Version 1.2.1, Forge 10.13.4.1558-1.7.10, and all I do is simply etch a second song onto a second records, but it will play the first record I etched instead.

**Comment by AngrySoundTech** [comment]
Going forward, I am no longer working on updates for 1.7.10, unless it is a major bug that needs addressing.

From what you say with "not everybody having the problem" It is likely that it is an issue with incompatibilities or the like on your end.

If this does turn out to be a widespread issue, then this issue will be re-opened and dealt with.
