### ISSUE TITLE
Music Doesn't Play

### ISSUE THREAD

**Issue by tankcr** [Stumblinbear/BetterRecords#41]
After properly Etching a record, used two different methods - A direct mp3 link, and also the method explained for hosting on Dropbox.
Take the Etched record to the record player
Click record on player - Nothing Happens

**Comment by tankcr** [comment]
Oh yes, using newest version for 1.12.2

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Stumblinbear/BetterRecords/issues/43

**Comment by NicholasFeldman** [comment]
Answered via discord, closing.
