### ISSUE TITLE
Crash when opening record etcher before library is loaded

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Stumblinbear/BetterRecords#43]
Here is a video
https://youtu.be/N5PSdIpKPVk

Here is a crash log
https://gist.github.com/P3rf3ctXZer0/cb0846ffde09a48a70881b793dc50604

Here is a full log
https://gist.github.com/P3rf3ctXZer0/1162ff7afc67e443e1612a6db31d610b

**Comment by NicholasFeldman** [comment]
Please do not link from unrelated issues.

In any case, this is interesting, as it doesn't seem to happen with other people, or in my testing environment.

Occurs in GuiRecordEtcher::drawGuiContainerBackgroundLayer#L349:

```java
 Color color = new Color(ClientProxy.Companion.getDefaultLibrary().get(offsetI).color);
```

Could you post the contents of your `%MINECRAFT_DIR%/betterrecords/localLibrary.json`?

**Comment by P3rf3ctXZer0** [comment]
yes

[betterrecords.zip](https://github.com/Stumblinbear/BetterRecords/files/1584575/betterrecords.zip)
