### ISSUE TITLE
Crash on Startup - Minecraft Dedicated Server 1.12.2 - 14.23.1.2587 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Stumblinbear/BetterRecords#50]
Forgelin-1.6.0.jar
BetterRecords-1.12.2-1.5.1.jar

Crash Log
https://gist.github.com/P3rf3ctXZer0/9ac8e995bb5f82b3d238d63544e9f604

Early Startup Log
https://gist.github.com/P3rf3ctXZer0/0087c066a274e1b55875a0a1111a47d1

Latest Log
https://gist.github.com/P3rf3ctXZer0/37c72bf3a67280f78a1b009093cdf12d

**Comment by NicholasFeldman** [comment]
Hotfix pending approval on Curse

**Comment by NicholasFeldman** [comment]
The Hotfix has been released, and is available on Curse: https://minecraft.curseforge.com/projects/better-records/files/2519498
