### ISSUE TITLE
Server Crash - End Track Initialzation failed when removing records on dedicated server (May also affect singleplayer) 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Stumblinbear/BetterRecords#51]
Song not stopping when record is removed 

Weird error when logging off dedicated server 
https://gist.github.com/P3rf3ctXZer0/d41fe1f2989b44d752286e9de36122ff

Server Crash
https://gist.github.com/P3rf3ctXZer0/78611ab408b6a35e481a4da26eb2619a

Early Startup
https://gist.github.com/P3rf3ctXZer0/1725e355a74830899df2498654a6dcbd

Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1234637136 bytes (1177 MB) / 3731881984 bytes (3559 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms1g -Xmx4g
	IntCache: cache: 0, tcache: 4, allocated: 8, tallocated: 60
FML: MCP 9.42 Powered by Forge 14.23.1.2587 143 mods loaded, 143 mods active

| UCHIJAAAA | forgelin                              | 1.6.0                  | Forgelin-1.6.0.jar                                    | None                                     |
| UCHIJAAAA | betterrecords | 1.12.2-1.5.2 | BetterRecords-1.12.2-1.5.2.jar

**Comment by NicholasFeldman** [comment]
Can you describe a bit more the issue?
You say the song is not stopping when the record is removed, but does the server crash as well?

**Comment by P3rf3ctXZer0** [comment]
So I played a track
It was playing for a while and I was going to change tracks but I removed track and it kept playing
I thought maybe if I put the track back it would stop
It didn't
I logged out that created this client side log
https://gist.github.com/P3rf3ctXZer0/d41fe1f2989b44d752286e9de36122ff

I logged back in and that crashed the server.

**Comment by NicholasFeldman** [comment]
Interesting. I'm trying to re-create this, but the song will only not stop playing about once every ten times.

This is likely due to old issues in the SoundHandler, which is the only part of the mod I have yet to re-write or modify since taking over.

I'm going to slate this for the next release, which I'm trying to get pushed out as fast as possible to fix the SoundHandler and a few other issues that have popped up here and there, and get everything hopefully rock solid and stable, since we've had a lot of code churn recently.

**Comment by NicholasFeldman** [comment]
Accelerating this to get out with a hotfix, I managed to narrow down the issue

**Comment by NicholasFeldman** [comment]
[Thank you for the issue and your patience, a new version with the fix has been released](https://minecraft.curseforge.com/projects/better-records/files/2520061)

**Comment by NicholasFeldman** [comment]
Note that the error when disconnecting from the server is harmless, as the thread spawned to update your music dies. This will be fixed in the next update however, with #45
