### ISSUE TITLE
Issue with volume radius on server

### ISSUE THREAD

**Issue by xhatz** [Stumblinbear/BetterRecords#52]
BetterRecords: `1.5.2`  
Forge: `2555`

# Issue
Hello! I'm running a forge server, and whenever I start a music, I can hear it from anywhere, even without speakers... (no fading out)

Also (not sure though): After a song is downloaded, it is played but cannot be stopped by removing the disk. Doing so plays it twice.

Thank you!

**Comment by NicholasFeldman** [comment]
[Thank you for the issue and your patience, a new version with the fix has been released](https://minecraft.curseforge.com/projects/better-records/files/2520061)

**Comment by xhatz** [comment]
Thank YOU for your awesome mod and for your superspeed fixing :3!

**Comment by NicholasFeldman** [comment]
No worries, thanks for the report. It will be available as soon as curse approves the file
