### ISSUE TITLE
Getting kicked from Server when someone trys too etch.

### ISSUE THREAD

**Issue by Epiixz** [Stumblinbear/BetterRecords#55]
BetterRecords: BetterRecords-1.10.2-1.5.0-beta.4.jar
Forge: 1.10.2 - 12.18.3.2511

# Issue
Cant itch records on server. Everytime someone on the server tries too etch it kicks them.

# Steps to Reproduce
1.Try to etch an record on a server.
2....
3. Profit

Link to crash log: <Preferably Gist or Pastebin>

**Comment by NicholasFeldman** [comment]
This is the old repo, and this issue was fixed in a later version.
